"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { Navbar } from "@/components/Navbar";
import { navItems } from "@/utils/navitems";
import { Infobar } from "@/components/Infobar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            /** Put your mantine theme override here */
            colorScheme: "light",
          }}
        >
          <Infobar />
          <Navbar links={navItems} />

          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
